development:
  adapter: sqlite3
  database: ":memory:"
  timeout: 5000

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 5000

production:
  adapter: sqlite3
  database: ":memory:"
  timeout: 5000
